from . import res_company_inherit
from . import custom_pop_message
from . import hr_payslip_indemnities
from . import hr_contract_inherit
from . import hr_salary_rule_inherit
from . import hr_payslip_inherit
from . import hr_employee_inherit
from . import hr_loans_line
from . import res_partner
from . import bordereau_cnss
from . import bordereau_payment
from . import livre_paie
from . import etat_9421
